# Generated by Django 5.2.7 on 2025-10-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalinfo', '0002_specialty_doctorspecialty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specialty',
            new_name='Specialist',
        ),
    ]
