# Generated by Django 5.2.7 on 2025-11-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalinfo', '0003_rename_specialty_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password_hash',
        ),
    ]
