# Generated by Django 5.2.7 on 2025-12-01 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalinfo', '0004_remove_patient_password_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_date',
            new_name='appointmentdate',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_id',
            new_name='appointmentid',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_id',
            new_name='deptid',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_id',
            new_name='doctorid',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='contact_number',
            new_name='contactnumber',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='created_at',
            new_name='createdat',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_id',
            new_name='hospitalid',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='patientid',
        ),
        migrations.RenameField(
            model_name='specialist',
            old_name='specialty_id',
            new_name='specialtyid',
        ),
    ]
